[alias]
kbuild = "build --target x86_64-unknown-uefi -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem"
uefi = "run --package disk_image -- /workspaces/rustos_uefi/uefi-app/target/x86_64-unknown-uefi/debug/uefi-app.efi"